### ISSUE TITLE
Element is not defined

### ISSUE THREAD

**Issue by Turalmehdiyev** [g787543/infinite-react-carousel#10]
Element is not defined
ReferenceError: Element is not defined
    at Object.<anonymous> (/media/psf/wetravel-in-docker/ssr-next/node_modules/infinite-react-carousel/lib/carousel/types.js:142:80)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/media/psf/wetravel-in-docker/ssr-next/node_modules/infinite-react-carousel/lib/carousel/slider.js:24:14)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)

Didn't work the previous solution suggestion. 
https://github.com/g787543/infinite-react-carousel/issues/5

**Comment by g787543** [comment]
Hi @Turalmehdiyev 

Can you give me your code or implement this issue with [codesandbox](https://codesandbox.io/s/infinite-react-carousel-hwghe)?
I don't know how you got this error.

**Comment by Turalmehdiyev** [comment]
Hi,
The software that I want use it is really huge, in total 2GB of codebase,
even cause of the privacy concern can't share it. But as I see many people
see this issue on their project.
I have worked with many many libraries in life, As I see There could be a
conflict with different library, Somehow "Element" becomes null. (You used
it for prevArrow, nextArrow functions.)

It would be great if you can fix this issue, and let me know, cause it's
one of the best libraries that fits my project. Thanks. Regards

**Comment by g787543** [comment]
Hi, Are you use SSR to render?

**Comment by Turalmehdiyev** [comment]
Hi,

Yes, I use SSR.

**Comment by g787543** [comment]
Got it, I will try to fix it.

**Comment by Turalmehdiyev** [comment]
Thanks in advance. Good luck!
