### ISSUE TITLE
Element is not defined

### ISSUE THREAD

**Issue by Gr8z** [g787543/infinite-react-carousel#5]
I get this error when I try out the demo example.

```
Element is not defined
ReferenceError: Element is not defined
    at Object.<anonymous> (d:\Scripts\BotBind\node_modules\infinite-react-carousel\lib\carousel\types.js:142:80)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (d:\Scripts\BotBind\node_modules\infinite-react-carousel\lib\carousel\slider.js:24:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by g787543** [comment]
Hi @Gr8z,

Can you use [this](https://codesandbox.io/s/infinite-react-carousel-hwghe) to implement this error?
or maybe you can give me your code

thank you.
